---
parser: babel-eslint

extends: eslint-config-shakacode

plugins:
#  - jest
  - react

#globals:
#  __DEBUG_SERVER_ERRORS__: true
#  __SERVER_ERRORS__: true

env:
  browser: true
#  jest/globals: true
  node: true

rules:
  import/extensions: [2, { js: "never", jsx: "never" }]
  function-paren-newline: ["error", "consistent"]

  # Good idea, but let's go to flow before fixing all these
  react/forbid-prop-types: 0
  jsx-a11y/href-no-hash: 0

  jsx-a11y/anchor-is-valid: off

settings:
  import/resolver:
    webpack:
      config: 'config/webpack/development.js'